---
- name: "Install app node"
  hosts: aula
  become: yes
  vars:
    path_app: /usr/app
  tasks:
    - name: "1 - Cria o diretorio"
      file:
        path: "{{path_app}}"
        state: directory
        mode: '0755'

    - name: "2 - Instala a dependencia unzip"
      package:
        name:
          - unzip
        state: present

    - name: "3 - Download e Descompactar"
      unarchive:
        src: https://github.com/bgsouza/app_node2/archive/master.zip
        dest: "{{path_app}}"
        remote_src: yes

   # - name: "4 - Compilando app - npm install"

   # - name: "5 - Gerenciador node pm2"

   # - name: "6 - Rodar app"
