---
- name: Upload Simple File
  hosts: aula
  become: yes
  gather_facts: yes
  vars:
    file_src: teste.txt
    file_dest: /usr/src
    mode: 0777
  tasks:
    - name: Upload file
      template:
        src: "{{file_src}}"
        dest: "{{file_dest}}"
      register: upload_file

    - name: alterando conteudo do arquivo
      blockinfile:
        path: '{{file_dest}}/{{file_src}}'
        insertafter: ''
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        content: |
          conteudo editado pelo ansible
      when: upload_file is success